---
- name: Allow qBittorrent through firewalld
  ansible.posix.firewalld:
    service: questdb
    zone: public
    permanent: true
    state: enabled
  notify:
    - Reload firewalld

- name: Create directory for QuestDB
  ansible.builtin.file:
    path: /var/lib/questdb
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Ensure docker-compose directory exists
  ansible.builtin.file:
    path: /opt/questdb
    state: directory
    mode: "0755"

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/questdb/docker-compose.yml
    mode: "0644"

