---
duckdns_domain: kism
proxmox_target_node: pvewill
target_host_ip_address: 10.42.0.2
target_host_mac_address: 4A:24:F7:A8:5C:5C
proxmox_ct_disk: "local-lvm:10"
proxmox_ct_memory: 512
proxmox_ct_cores: 1
secret_cloudflare_api_dns: "{{ lookup('bitwarden.secrets.lookup', '403c608c-85a3-487f-92ec-b22200708cd5') }}"
secret_cloudflare_api_dns_zone: "{{ lookup('bitwarden.secrets.lookup', 'ffba4513-7464-4a57-9961-b3ec0044a7e5') }}"
