---
- name: Allow victoriametrics through firewalld
  ansible.posix.firewalld:
    service: victoriametrics
    zone: public
    permanent: true
    state: enabled
  notify:
    - Reload firewalld

- name: Create directory for victoriametrics
  ansible.builtin.file:
    path: /var/lib/victoriametrics
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Ensure docker-compose directory exists
  ansible.builtin.file:
    path: /opt/victoriametrics
    state: directory
    mode: "0755"

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/victoriametrics/docker-compose.yml
    mode: "0644"

