---
configure_packages_to_install:
  - at
  - ca-certificates
  - file
  - git
  - htop
  - iotop
  - ncdu
  - nload
  - rsync
  - tar
  - tmux
  - tree
  - unzip
  - vim
  - wget
  - which

configure_packages_to_remove:
  - cockpit
  - cups
