---
- name: Remove old apt lists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - influxdb.list
    - telegraf.list
    - influxdata.list

- name: Copy over apt key
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /tmp/influxdata-archive.key
    mode: "0644"

- name: Remove old key if exists
  ansible.builtin.file:
    path: /tmp/influxdata-archive.key.gpg
    state: absent

- name: Dearmour the key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /tmp/influxdata-archive.key.gpg /tmp/influxdata-archive.key
  changed_when: false

- name: Copy the key to the correct location
  ansible.builtin.copy:
    src: /tmp/influxdata-archive.key.gpg
    dest: /usr/share/keyrings/influxdata-archive.gpg
    mode: "0644"
    remote_src: true

- name: Add Telegraf repository {{ ansible_distribution | lower }}
  ansible.builtin.apt_repository:
    repo: |-
      deb
      [signed-by=/usr/share/keyrings/influxdata-archive.gpg]
      https://repos.influxdata.com/{{ ansible_distribution | lower }} stable main
    filename: influxdata
    state: present
