---
- name: Copy over influxdb repo
  ansible.builtin.copy:
    src: files/influxdb.repo
    dest: /etc/yum.repos.d/influxdb.repo
    mode: "644"

- name: Remove old file lol
  ansible.builtin.file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-influxdata
    state: absent

- name: Install telegraf
  ansible.builtin.dnf:
    name: telegraf
    state: present
