---
# https://repo.jellyfin.org/?path=/server/linux/latest-stable/amd64
configure_jellyfin_adhoc_version: 10.11.5
# https://github.com/jellyfin/jellyfin-ffmpeg/releases
configure_jellyfin_adhoc_ffmpeg_version: 7.1.3-1
